<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->

 <? 
	include 'frisco_db.inc';
	
?>




<html>
	<head>
		<title>Sushi Damu Frisco</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../assets/css/main.css" />
		<link rel="stylesheet" href="../assets/css/main_add.css" />
		<noscript><link rel="stylesheet" href="../assets/css/noscript.css" /></noscript>
		
		
		
		
		
		<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-8S3D7NM0R9"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-8S3D7NM0R9');
</script>
		
		
		
		
		
		
		
		
		
		
		
		
		
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner" align="center">

							<!-- Logo -->
								<a href="index.php" class="logo">
									<!--<span class="symbol"><img src="images/SUSHI DAMU LOGO.jpg" alt="" />--></span><h1 class="title">Sushi Damu FRISCO</h1>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<!--
						<h2>Menu</h2>
						-->
						<ul>
							<li><a href="../index.php">Home</a></li>
							<li><a href="index.php">Frisco</a></li>							
							<li><a href="_hour.php">HOUR</a></li>
							<li><a href="_locations.php">LOCATIONS</a></li>
						</ul>
					</nav>