

 <? 
	include 'frisco_db.inc';
	
?>




<html>
	<head>
		<title>Sushi Damu Frisco admin</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="../../assets/css/main.css" />
		<link rel="stylesheet" href="../../assets/css/main_add.css" />
		<noscript><link rel="stylesheet" href="../../assets/css/noscript.css" /></noscript>
		
	
		
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner" align="center">

							<!-- Logo -->
								<a href="00.index.php" class="logo">
									<!--<span class="symbol"><img src="images/SUSHI DAMU LOGO.jpg" alt="" />--></span><h1 class="title">Sushi Damu FRISCO Admin </h1>
								</a>

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<!--
						<h2>Menu</h2>
						-->
						<ul>
							<li><a href="1.list.php">List</a></li>
							<li><a href="1.list_notice.php">Notice List</a></li>							
							<li><a href="sales.php">Sales</a></li>
							<li><a href="tip.php">Tip</a></li>
						</ul>
					</nav>